routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return redirect()->route('login');
});

Route::group(['prefix' => 'api'], function () {
    Route::get('group', [
        'as'   => 'group',
        'uses' => 'APIController@getGroup',
    ]);
    Route::get('task/{group}', [
        'as'   => 'task',
        'uses' => 'APIController@getTaskByGroupName',
    ]);
    Route::get('task/{taskId}/{status}', [
        'as'   => 'task',
        'uses' => 'APIController@updateStatus',
    ]);
});
Route::group(['middleware' => ['adminauth']], function () {
	Route::get('dashboard', [
        'as'   => 'dashboard',
        'uses' => 'DashboardController@index',
    ]);

    Route::group(['prefix' => 'change'], function () {
        Route::get('password', array(
            'as'   => 'changepassword.get',
            'uses' => 'UserController@getChangePassword',
        ));

        Route::post('password', array(
            'as'   => 'changepassword.post',
            'uses' => 'UserController@postChangePassword',
        ));
    });

    //Group routes start
    Route::group(['prefix' => 'group'], function () {
        Route::delete('delete', [
            'as'   => 'group.delete',
            'uses' => 'GroupController@delete',
        ]);

        Route::get('taskAssign', [
            'as'   => 'taskAssign',
            'uses' => 'GroupController@taskAssign',
        ]);
    });
    Route::resource('group', 'GroupController', ['except' => 'destroy', 'show']);
    //Group routes end
    
    //Task routes start
    Route::group(['prefix' => 'task'], function () {
        Route::delete('delete', [
            'as'   => 'task.delete',
            'uses' => 'TaskController@delete',
        ]);
    });
    Route::resource('task', 'TaskController', ['except' => 'destroy', 'show']);
    //Task routes end
    
    //Task User routes start
    Route::group(['prefix' => 'taskUser'], function () {
        Route::delete('delete', [
            'as'   => 'taskUser.delete',
            'uses' => 'TaskUserController@delete',
        ]);
    });
    Route::resource('taskUser', 'TaskUserController', ['except' => 'destroy', 'show']);
    //Task User routes end
    
    Route::get('taskAssign', [
        'as'   => 'taskAssign',
        'uses' => 'GroupController@taskAssign',
    ]);

    Route::post('taskAssign', [
        'as'   => 'taskAssign',
        'uses' => 'GroupController@taskAssignStore',
    ]);

    Route::get('groupAssign', [
        'as'   => 'groupAssign',
        'uses' => 'GroupController@groupAssign',
    ]);

    Route::post('groupAssign', [
        'as'   => 'groupAssign',
        'uses' => 'GroupController@groupAssignStore',
    ]);

    Route::get('logout', [
        'as'   => 'logout',
        'uses' => 'Auth\LoginController@logout',
    ]);
});

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Model\GroupTask;
use App\Model\Task;
use App\Model\TaskGroup;
use App\Model\TaskUser;
use App\Model\UserGroup;
use Illuminate\Http\Request;
use Validator;
use View;

class GroupController extends Controller
{
    /**
     * [__construct description]
     */
    public function __construct()
    {
        parent::__construct();
        $this->viewPath = "group";
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        View::share("title", "Group");

        if ($request->ajax()) {
            $whereStr    = '1 = ?';
            $whereParams = [1];

            if ($request->has('sSearch')) {
                $search = trim(trim($request->get('sSearch')));
                $whereStr .= " and ( name like '%{$search}%'"
                    . ")";
            }

            $columns = ['task_group.id', 'task_group.name'];

            $group = TaskGroup::select($columns)
                ->whereRaw($whereStr, $whereParams)
                ->groupBy("task_group.id");

            $groupCcount = TaskGroup::select('id')
                ->whereRaw($whereStr, $whereParams)
                ->count();

            if ($request->has('iDisplayStart') && $request->get('iDisplayLength') != '-1') {
                $group = $group->take($request->get('iDisplayLength'))->skip($request->get('iDisplayStart'));
            }

            if ($request->has('iSortCol_0')) {
                $sql_order = '';
                for ($i = 0; $i < $request->get('iSortingCols'); $i++) {
                    $column = $columns[$request->get('iSortCol_' . $i)];
                    if (false !== ($index = strpos($column, ' as '))) {
                        $column = substr($column, 0, $index);
                    }
                    $group = $group->orderBy($column, $request->get('sSortDir_' . $i));
                }
            }

            $group = $group->get();

            $response['iTotalDisplayRecords'] = $groupCcount;
            $response['iTotalRecords']        = $groupCcount;
            $response['sEcho']                = intval($request->get('sEcho'));
            $response['aaData']               = $group;
            return $response;
        }

        return view($this->viewPath . '.index');
    }

    /**
     * [create description]
     * @return [type] [description]
     */
    public function create()
    {
        View::share("title", "Group");
        return view($this->viewPath . '.create');
    }

    /**
     * [store description]
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function store(Request $request)
    {
        $data  = $request->all();
        $rules = [
            'name' => "required|unique:task_group,name",
        ];
        $message = [
            'name.unique' => 'The group must be unique',
        ];
        $validator = Validator::make($data, $rules, $message);
        if ($validator->fails()) {
            return back()->withInput()
                ->withErrors($validator)
                ->with('message_type', 'danger')
                ->with('message', 'There were some error try again');
        }

        TaskGroup::insert([
            'name'       => $request->name,
            "created_at" => date("Y-m-d H:i:s"),
            "updated_at" => date("Y-m-d H:i:s"),
        ]);

        return back()->with('message_type', 'success')
            ->with('message', 'Group Store Successfully');
    }

    /**
     * [edit description]
     * @param  [type] $id [description]
     * @return [type]     [description]
     */
    public function edit($id)
    {
        View::share("title", "Group");
        $group = TaskGroup::where('id', $id)->first();
        return view($this->viewPath . '.edit', compact('group'));
    }

    /**
     * [update description]
     * @param  Request $request [description]
     * @param  [type]  $id      [description]
     * @return [type]           [description]
     */
    public function update(Request $request, $id)
    {
        $data  = $request->all();
        $rules = [
            'name' => "required|unique:task_group,name,$id,id",
        ];
        $validator = Validator::make($data, $rules);
        if ($validator->fails()) {
            return back()->withInput()
                ->withErrors($validator)
                ->with('message_type', 'danger')
                ->with('message', 'There were some error try again');
        }
        TaskGroup::where('id', $id)->update(['name' => $request->name]);
        return back()->with('message_type', 'success')
            ->with('message', 'Group Updated Successfully');
    }

    /**
     * [delete description]
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function delete(Request $request)
    {
        View::share("title", "Group");
        $ids = $request->id;
        if (!is_array($ids)) {
            $ids = explode(",", $ids);
        }
        GroupTask::whereIn('group_id', $ids)->delete();
        TaskGroup::whereIn('id', $ids)->delete();
        return response()->json(['success' => true], 200);
    }

    /**
     * [taskAssign description]
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function taskAssign(Request $request)
    {
        View::share("title", "Assing Task To Group");
        $groups = TaskGroup::pluck("name", "id")->all();
        $tasks  = Task::pluck("name", "id")->all();
        return view($this->viewPath . '.assign', compact('groups', 'tasks'));
    }

    /**
     * [taskAssignStore description]
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function taskAssignStore(Request $request)
    {
        $data = $request->all();

        $rules = [
            'group_id' => "required",
            'task_id'  => "required",
        ];
        $message = [
            'group_id.required' => 'This fields is required',
            'task_id.unique'    => 'This fields is required',
        ];
        $validator = Validator::make($data, $rules, $message);
        if ($validator->fails()) {
            return back()->withInput()
                ->withErrors($validator)
                ->with('message_type', 'danger')
                ->with('message', 'There were some error try again');
        }

        $allTask = GroupTask::where("group_id", $request->group_id)->pluck("task_id")->all();

        $final = [];
        foreach ($data['task_id'] as $key => $value) {
            if (!in_array($value, $allTask)) {
                $final[$key]['group_id']   = $data['group_id'];
                $final[$key]['task_id']    = $value;
                $final[$key]['created_at'] = date("Y-m-d H:i:s");
                $final[$key]['updated_at'] = date("Y-m-d H:i:s");
            }
        }

        if (!empty($final)) {
            foreach (array_chunk($final, 500) as $key => $insertRow) {
                GroupTask::insert($insertRow);
            }
        }

        return back()->with('message_type', 'success')
            ->with('message', 'Group Task Updated Successfully');
    }

    /**
     * [groupAssign description]
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function groupAssign(Request $request)
    {
        View::share("title", "Assing Group To User");
        $groups = TaskGroup::pluck("name", "id")->all();
        $users  = TaskUser::pluck("first_name", "id")->all();
        return view($this->viewPath . '.user', compact('groups', 'users'));
    }

    /**
     * [groupAssignStore description]
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function groupAssignStore(Request $request)
    {
        $data = $request->all();

        $rules = [
            'group_id' => "required",
            'user_id'  => "required",
        ];
        $message = [
            'group_id.required' => 'This fields is required',
            'user_id.unique'    => 'This fields is required',
        ];
        $validator = Validator::make($data, $rules, $message);
        if ($validator->fails()) {
            return back()->withInput()
                ->withErrors($validator)
                ->with('message_type', 'danger')
                ->with('message', 'There were some error try again');
        }

        $allTask = UserGroup::where("group_id", $request->group_id)->pluck("user_id")->all();

        $final = [];
        foreach ($data['user_id'] as $key => $value) {
            if (!in_array($value, $allTask)) {
                $final[$key]['group_id']   = $data['group_id'];
                $final[$key]['user_id']    = $value;
                $final[$key]['created_at'] = date("Y-m-d H:i:s");
                $final[$key]['updated_at'] = date("Y-m-d H:i:s");
            }
        }

        if (!empty($final)) {
            foreach (array_chunk($final, 500) as $key => $insertRow) {
                UserGroup::insert($insertRow);
            }
        }

        return back()->with('message_type', 'success')
            ->with('message', 'Group Task Updated Successfully');
    }
}

resources/views/group/assign.blade.php
@extends($layoutTheme)
@section('content')
<div class="box box-warning">
	<div class="box-header with-border">
		<i class="fa fa-compass"></i>
		<h3 class="box-title">Assign Task To Group</h3>
	</div>
	<div class="box-body">
		<div class="row">
			{!! Form::open(array('url'=>route('taskAssign'),'class' => 'form-horizontal')) !!}
			<div class="form-group required">
				<label class="col-sm-2 control-label">Group :-</label>
				<div class="col-sm-6">
					{!! Form::select('group_id',['' => '- Select Group -']+$groups,Input::get('group_id',null),array('class'=>'form-control select2','id' => 'group_id')) !!}
					{!! $errors->first('group_id','<span class="help-inline text-danger">:message</span>') !!}
				</div>
			</div>

			<div class="form-group required">
				<label class="col-sm-2 control-label">Task :-</label>
				<div class="col-sm-6">
					{!! Form::select('task_id',$tasks,Input::get('task_id',null),array('class'=>'form-control select2','id' => 'task_id','multiple'=>'multiple','name'=> 'task_id[]')) !!}
					{!! $errors->first('name','<span class="help-inline text-danger">:message</span>') !!}
				</div>
			</div>
		</div>
	</div>
	<div class="box-footer">
		<div class="form-group">
			<div class="col-sm-offset-2">
				<button type="submit" class="btn btn-success">
					<i class="fa fa-sliders" aria-hidden="true"></i> Save
				</button>
				<button type="reset" class="btn btn-default">
					<i class="fa fa-trash" aria-hidden="true"></i> Reset
				</button>
			</div>
		</div>
	</div>
	{!! Form::close() !!}
	<div id="spin" class="overlay" style="display:none;">
		<i class="fa fa-spin fa-spinner"></i>
	</div>
	<!-- /.box-body -->
</div>
@stop
@section('script')
<script type="text/javascript">
	$('form').submit(function(){
		myShow();
	});
</script>
@stop

resources/views/group/create.blade.php
@extends($layoutTheme)
@section('content')
<div class="box box-warning">
	<div class="box-header with-border">
		<i class="fa fa-compass"></i>
		<h3 class="box-title">Create Group</h3>
		<div class="pull-right box-tools">
			<a class="btn btn-success btn-sm" data-toggle="tooltip" title="Back" href="{!!route('group.index')!!}"><i class="fa fa-lg fa fa-arrow-left"></i></a>
		</div>
		<!-- /. tools -->
	</div>
	<div class="box-body">
		<div class="row">
			{!! Form::open(array('url'=>route('group.store'),'class' => 'form-horizontal')) !!}
			@include("group.form")
		</div>
	</div>
	<div class="box-footer">
		<div class="form-group">
			<div class="col-sm-offset-2">
				<button type="submit" class="btn btn-success">
					<i class="fa fa-sliders" aria-hidden="true"></i> Save
				</button>
				<button type="reset" class="btn btn-default">
					<i class="fa fa-trash" aria-hidden="true"></i> Reset
				</button>
			</div>
		</div>
	</div>
	{!! Form::close() !!}
	<div id="spin" class="overlay" style="display:none;">
		<i class="fa fa-spin fa-spinner"></i>
	</div>
	<!-- /.box-body -->
</div>
@stop
@section('script')
<script type="text/javascript">
	$('form').submit(function(){
		myShow();
	});
</script>
@stop

resources/views/group/edit.blade.php
@extends($layoutTheme)
@section('content')

<div class="box box-warning">
	<div class="box-header with-border">
		<h3 class="box-title">Edit Distributor</h3>
		<div class="pull-right box-tools">
			<a class="btn btn-success btn-sm" data-toggle="tooltip" title="Back" href="{{route('group.index')}}"><i class="fa fa-lg fa fa-arrow-left"></i></a>
		</div>
		<!-- /. tools -->
	</div>
	<div class="box-body">
		<div class="row">
			{{ Form::model($group,array('url'=>route('group.update',$group->id),'class' => 'form-horizontal','method' => 'PATCH' )) }}
			@include("group.form")
		</div>
	</div>
	<div class="box-footer">
		<div class="form-group">
			<div class="col-sm-offset-2">
				<button type="submit" class="btn btn-success">
					<i class="fa fa-sliders" aria-hidden="true"></i> Save
				</button>
				<button type="reset" class="btn btn-default">
					<i class="fa fa-trash" aria-hidden="true"></i> Reset
				</button>
			</div>
		</div>
	</div>
	{{ Form::close() }}
	<div id="spin" class="overlay" style="display:none;">
		<i class="fa fa-spin fa-spinner"></i>
	</div>
	<!-- /.box-body -->
</div>
			
@stop
@section('script')
<script type="text/javascript">
	$('form').submit(function(){
		myShow();
	});
</script>
@stop

resources/views/group/form.blade.php
<div class="form-group required">
	<label class="col-sm-2 control-label">Group :-</label>
	<div class="col-sm-6">
		{!! Form::text('name',Input::old('name'),array('class'=>'form-control','placeholder'=>'Group Name')) !!}
		{!! $errors->first('name','<span class="help-inline text-danger">:message</span>') !!}
	</div>
</div>

resources/views/group/index.blade.php
@extends($layoutTheme)
@section('content')

<div class="box box-info">
    <div class="box-header with-border">
        <i class="fa fa-compass"></i>
        <h3 class="box-title">All Groups</h3>
        <div class="pull-right box-tools">
            <a class="btn btn-success btn-sm" id='add_product' data-toggle="tooltip" title="Add Groups" href="{{ route('group.create') }}"><i class="fa fa-fw fa-plus fa-lg"></i> </a>
        </div>
    </div>
    <div class="box-body">
        <table id='group' class="table table-condensed table-bordered table-hover" style="width:100%">
            <thead>
                <tr>
                    <th style="padding-left:20px;">No</th>
                    <th>Group</th>
                    <th>Action</th>
                </tr>
            </thead>
            <thead id="filters">
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <div id="spin" class="overlay" style="display:none;">
        <i class="fa fa-spin fa-spinner"></i>
    </div>
    <!-- /.box-body -->
</div>
@stop

@section('script')

<script type="text/javascript">

$(function() {

    group = $('#group').dataTable({
        "bProcessing": false,
        "bServerSide": true,
        "bStateSave": true,
        "autoWidth": true,
        "sAjaxSource": "{{URL::route('group.index')}}",
        "sPaginationType": "listbox",
        "aaSorting": [
            [1, "asc"]
        ],
        "oLanguage": {
          "sLengthMenu": "Display _MENU_ records"
        },
        "aoColumns": [
        { "mData": "id",sWidth: "05%",},
        { "mData": "name",sWidth: "60%",},
        {
            mData: null,
            bSortable: false,
            sWidth: "5%",
            sClass: "text-center",
            mRender: function(v, t, o) {
                var editurl = '{{ route("group.edit", ":id") }}';
                editurl = editurl.replace(':id',o['id']);
                var act_html = "<a href='"+editurl+"' data-toggle='tooltip' title='Edit Group' data-placement='top' class='btn btn-primary btn-sm'><i class='fa fa-fw fa-edit fa-lg'></i></a>"
                                +"&nbsp"
                                +"<a href='javascript:void(0)' data-name='"+o['name']+"' data-id='"+o['id']+"'  data-type='group' data-toggle='tooltip' title='Delete Group' data-placement='top' class='btn btn-sm btn-danger btn-delete'><i class='fa fa-fw fa-trash-o fa-lg'></i></a>"
                return act_html;
            }
        }, ],
        fnPreDrawCallback: function() {
            myShow();
        },
        fnDrawCallback: function(oSettings) {
            myHide();
        },
        fnRowCallback : function(nRow, aData, iDisplayIndex){
           $("td:first", nRow).html(iDisplayIndex +1);
           return nRow;
        },
    });

    group.fnSetFilteringDelay(1000);

    $("#group thead#filters input:text").donetyping(function() {
        group.fnFilter(this.value, $("#group thead#filters input:text").index(this));
    });
});
</script>
@stop

resources/views/group/user.blade.php
@extends($layoutTheme)
@section('content')
<div class="box box-warning">
	<div class="box-header with-border">
		<i class="fa fa-compass"></i>
		<h3 class="box-title">Assign User To Group</h3>
	</div>
	<div class="box-body">
		<div class="row">
			{!! Form::open(array('url'=>route('groupAssign'),'class' => 'form-horizontal')) !!}
			<div class="form-group required">
				<label class="col-sm-2 control-label">Group :-</label>
				<div class="col-sm-6">
					{!! Form::select('group_id',['' => '- Select Group -']+$groups,Input::get('group_id',null),array('class'=>'form-control select2','id' => 'group_id')) !!}
					{!! $errors->first('group_id','<span class="help-inline text-danger">:message</span>') !!}
				</div>
			</div>

			<div class="form-group required">
				<label class="col-sm-2 control-label">User :-</label>
				<div class="col-sm-6">
					{!! Form::select('user_id',$users,Input::get('user_id',null),array('class'=>'form-control select2','id' => 'user_id','multiple'=>'multiple','name'=> 'user_id[]')) !!}
					{!! $errors->first('name','<span class="help-inline text-danger">:message</span>') !!}
				</div>
			</div>
		</div>
	</div>
	<div class="box-footer">
		<div class="form-group">
			<div class="col-sm-offset-2">
				<button type="submit" class="btn btn-success">
					<i class="fa fa-sliders" aria-hidden="true"></i> Save
				</button>
				<button type="reset" class="btn btn-default">
					<i class="fa fa-trash" aria-hidden="true"></i> Reset
				</button>
			</div>
		</div>
	</div>
	{!! Form::close() !!}
	<div id="spin" class="overlay" style="display:none;">
		<i class="fa fa-spin fa-spinner"></i>
	</div>
	<!-- /.box-body -->
</div>
@stop
@section('script')
<script type="text/javascript">
	$('form').submit(function(){
		myShow();
	});
</script>
@stop