routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return redirect()->route('login');
});

Route::group(['prefix' => 'api'], function () {
    Route::get('group', [
        'as'   => 'group',
        'uses' => 'APIController@getGroup',
    ]);
    Route::get('task/{group}', [
        'as'   => 'task',
        'uses' => 'APIController@getTaskByGroupName',
    ]);
    Route::get('task/{taskId}/{status}', [
        'as'   => 'task',
        'uses' => 'APIController@updateStatus',
    ]);
});
Route::group(['middleware' => ['adminauth']], function () {
	Route::get('dashboard', [
        'as'   => 'dashboard',
        'uses' => 'DashboardController@index',
    ]);

    Route::group(['prefix' => 'change'], function () {
        Route::get('password', array(
            'as'   => 'changepassword.get',
            'uses' => 'UserController@getChangePassword',
        ));

        Route::post('password', array(
            'as'   => 'changepassword.post',
            'uses' => 'UserController@postChangePassword',
        ));
    });

    //Group routes start
    Route::group(['prefix' => 'group'], function () {
        Route::delete('delete', [
            'as'   => 'group.delete',
            'uses' => 'GroupController@delete',
        ]);

        Route::get('taskAssign', [
            'as'   => 'taskAssign',
            'uses' => 'GroupController@taskAssign',
        ]);
    });
    Route::resource('group', 'GroupController', ['except' => 'destroy', 'show']);
    //Group routes end
    
    //Task routes start
    Route::group(['prefix' => 'task'], function () {
        Route::delete('delete', [
            'as'   => 'task.delete',
            'uses' => 'TaskController@delete',
        ]);
    });
    Route::resource('task', 'TaskController', ['except' => 'destroy', 'show']);
    //Task routes end
    
    //Task User routes start
    Route::group(['prefix' => 'taskUser'], function () {
        Route::delete('delete', [
            'as'   => 'taskUser.delete',
            'uses' => 'TaskUserController@delete',
        ]);
    });
    Route::resource('taskUser', 'TaskUserController', ['except' => 'destroy', 'show']);
    //Task User routes end
    
    Route::get('taskAssign', [
        'as'   => 'taskAssign',
        'uses' => 'GroupController@taskAssign',
    ]);

    Route::post('taskAssign', [
        'as'   => 'taskAssign',
        'uses' => 'GroupController@taskAssignStore',
    ]);

    Route::get('groupAssign', [
        'as'   => 'groupAssign',
        'uses' => 'GroupController@groupAssign',
    ]);

    Route::post('groupAssign', [
        'as'   => 'groupAssign',
        'uses' => 'GroupController@groupAssignStore',
    ]);

    Route::get('logout', [
        'as'   => 'logout',
        'uses' => 'Auth\LoginController@logout',
    ]);
});

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Model\Task;
use Illuminate\Http\Request;
use Validator;
use View;

class TaskController extends Controller
{
    /**
     * [__construct description]
     */
    public function __construct()
    {
        parent::__construct();
        $this->viewPath = "task";
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        View::share("title", "Task");

        if ($request->ajax()) {
            $whereStr    = '1 = ?';
            $whereParams = [1];

            if ($request->has('sSearch')) {
                $search = trim(trim($request->get('sSearch')));
                $whereStr .= " and ( name like '%{$search}%'"
                    . ")";
            }

            $columns = ['task.id as id', 'task.name','task.description','status'];

            $task = Task::select($columns)
                ->whereRaw($whereStr, $whereParams)
                ->groupBy("task.id");

            $taskCount = Task::select('id')
                ->whereRaw($whereStr, $whereParams)
                ->count();

            if ($request->has('iDisplayStart') && $request->get('iDisplayLength') != '-1') {
                $task = $task->take($request->get('iDisplayLength'))->skip($request->get('iDisplayStart'));
            }

            if ($request->has('iSortCol_0')) {
                $sql_order = '';
                for ($i = 0; $i < $request->get('iSortingCols'); $i++) {
                    $column = $columns[$request->get('iSortCol_' . $i)];
                    if (false !== ($index = strpos($column, ' as '))) {
                        $column = substr($column, 0, $index);
                    }
                    $task = $task->orderBy($column, $request->get('sSortDir_' . $i));
                }
            }

            $task = $task->get();

            $response['iTotalDisplayRecords'] = $taskCount;
            $response['iTotalRecords']        = $taskCount;
            $response['sEcho']                = intval($request->get('sEcho'));
            $response['aaData']               = $task;
            return $response;
        }

        return view($this->viewPath . '.index');
    }

    /**
     * [create description]
     * @return [type] [description]
     */
    public function create()
    {
        View::share("title", "Task");
        return view($this->viewPath . '.create');
    }

    /**
     * [store description]
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function store(Request $request)
    {
        $data  = $request->all();
        $rules = [
            'name'        => "required|unique:task,name",
            'description' => "required",
        ];
        $message = [
            'name.unique' => 'The task must be unique',
        ];
        $validator = Validator::make($data, $rules, $message);
        if ($validator->fails()) {
            return back()->withInput()
                ->withErrors($validator)
                ->with('message_type', 'danger')
                ->with('message', 'There were some error try again');
        }

        Task::insert([
            'name'        => $request->name,
            'description' => $request->description,
            "created_at"  => date("Y-m-d H:i:s"),
            "updated_at"  => date("Y-m-d H:i:s"),
        ]);

        return back()->with('message_type', 'success')
            ->with('message', 'Task Store Successfully');
    }

    /**
     * [edit description]
     * @param  [type] $id [description]
     * @return [type]     [description]
     */
    public function edit($id)
    {
        View::share("title", "Task");
        $task = Task::where('id', $id)->first();
        return view($this->viewPath . '.edit', compact('task'));
    }

    /**
     * [update description]
     * @param  Request $request [description]
     * @param  [type]  $id      [description]
     * @return [type]           [description]
     */
    public function update(Request $request, $id)
    {
        $data  = $request->all();
        $rules = [
            'name'        => "required|unique:task,name,$id,id",
            'description' => "required",
        ];
        $validator = Validator::make($data, $rules);
        if ($validator->fails()) {
            return back()->withInput()
                ->withErrors($validator)
                ->with('message_type', 'danger')
                ->with('message', 'There were some error try again');
        }
        Task::where('id', $id)->update(['name' => $request->name, 'description' => $request->description, 'updated_at' => date("Y-m-d H:i:s")]);
        return back()->with('message_type', 'success')
            ->with('message', 'Task Updated Successfully');
    }

    /**
     * [delete description]
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function delete(Request $request)
    {
        View::share("title", "Task");
        $ids = $request->id;
        if (!is_array($ids)) {
            $ids = explode(",", $ids);
        }
        Task::whereIn('id', $ids)->delete();
        return response()->json(['success' => true], 200);
    }
}

resources/views/task/create.blade.php
@extends($layoutTheme)
@section('content')
<div class="box box-warning">
	<div class="box-header with-border">
		<i class="fa fa-compass"></i>
		<h3 class="box-title">Create Task</h3>
		<div class="pull-right box-tools">
			<a class="btn btn-success btn-sm" data-toggle="tooltip" title="Back" href="{!!route('task.index')!!}"><i class="fa fa-lg fa fa-arrow-left"></i></a>
		</div>
		<!-- /. tools -->
	</div>
	<div class="box-body">
		<div class="row">
			{!! Form::open(array('url'=>route('task.store'),'class' => 'form-horizontal')) !!}
			@include("task.form")
		</div>
	</div>
	<div class="box-footer">
		<div class="form-group">
			<div class="col-sm-offset-2">
				<button type="submit" class="btn btn-success">
					<i class="fa fa-sliders" aria-hidden="true"></i> Save
				</button>
				<button type="reset" class="btn btn-default">
					<i class="fa fa-trash" aria-hidden="true"></i> Reset
				</button>
			</div>
		</div>
	</div>
	{!! Form::close() !!}
	<div id="spin" class="overlay" style="display:none;">
		<i class="fa fa-spin fa-spinner"></i>
	</div>
	<!-- /.box-body -->
</div>
@stop
@section('script')
<script type="text/javascript">
	$('form').submit(function(){
		myShow();
	});
</script>
@stop

resources/views/task/edit.blade.php
@extends($layoutTheme)
@section('content')

<div class="box box-warning">
	<div class="box-header with-border">
		<h3 class="box-title">Edit Task </h3>
		<div class="pull-right box-tools">
			<a class="btn btn-success btn-sm" data-toggle="tooltip" title="Back" href="{{route('task.index')}}"><i class="fa fa-lg fa fa-arrow-left"></i></a>
		</div>
		<!-- /. tools -->
	</div>
	<div class="box-body">
		<div class="row">
			{{ Form::model($task,array('url'=>route('task.update',$task->id),'class' => 'form-horizontal','method' => 'PATCH' )) }}
			@include("task.form")
		</div>
	</div>
	<div class="box-footer">
		<div class="form-group">
			<div class="col-sm-offset-2">
				<button type="submit" class="btn btn-success">
					<i class="fa fa-sliders" aria-hidden="true"></i> Save
				</button>
				<button type="reset" class="btn btn-default">
					<i class="fa fa-trash" aria-hidden="true"></i> Reset
				</button>
			</div>
		</div>
	</div>
	{{ Form::close() }}
	<div id="spin" class="overlay" style="display:none;">
		<i class="fa fa-spin fa-spinner"></i>
	</div>
	<!-- /.box-body -->
</div>
			
@stop
@section('script')
<script type="text/javascript">
	$('form').submit(function(){
		myShow();
	});
</script>
@stop

resources/views/task/form.blade.php
<div class="form-group required">
	<label class="col-sm-2 control-label">Task Title :-</label>
	<div class="col-sm-6">
		{!! Form::text('name',Input::old('name'),array('class'=>'form-control','placeholder'=>'Task Name')) !!}
		{!! $errors->first('name','<span class="help-inline text-danger">:message</span>') !!}
	</div>
</div>

<div class="form-group required">
	<label class="col-sm-2 control-label">Task Description :-</label>
	<div class="col-sm-6">
		{!! Form::textarea('description',Input::old('description'),array('class'=>'form-control','placeholder'=>'Task Description')) !!}
		{!! $errors->first('description','<span class="help-inline text-danger">:message</span>') !!}
	</div>
</div>

resources/views/task/index.blade.php
@extends($layoutTheme)
@section('content')

<div class="box box-info">
    <div class="box-header with-border">
        <i class="fa fa-compass"></i>
        <h3 class="box-title">All Tasks</h3>
        <div class="pull-right box-tools">
            <a class="btn btn-success btn-sm" id='add_product' data-toggle="tooltip" title="Add Tasks" href="{{ route('task.create') }}"><i class="fa fa-fw fa-plus fa-lg"></i> </a>
        </div>
    </div>
    <div class="box-body">
        <table id='task' class="table table-condensed table-bordered table-hover" style="width:100%">
            <thead>
                <tr>
                    <th style="padding-left:20px;">No</th>
                    <th>Task</th>
                    <th>Task Description</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <thead id="filters">
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <div id="spin" class="overlay" style="display:none;">
        <i class="fa fa-spin fa-spinner"></i>
    </div>
    <!-- /.box-body -->
</div>
@stop

@section('script')

<script type="text/javascript">

$(function() {

    task = $('#task').dataTable({
        "bProcessing": false,
        "bServerSide": true,
        "bStateSave": true,
        "autoWidth": true,
        "sAjaxSource": "{{URL::route('task.index')}}",
        "sPaginationType": "listbox",
        "aaSorting": [
            [1, "asc"]
        ],
        "oLanguage": {
          "sLengthMenu": "Display _MENU_ records"
        },
        "aoColumns": [
        { "mData": "id",sWidth: "05%",},
        { "mData": "name",sWidth: "15%",},
        { "mData": "description",sWidth: "30%",bSortable: false,},
        {
            mData:'status',
            bSortable:false,
            sClass : 'text-center no_click_action',
            sWidth: "15%",
            mRender : function(v,t,o){
                if (v == 0) {
                    var act_html = "<span class='badge bg-green'>Active</span></a>";
                } else {
                    var act_html = "<span class='badge bg-red'>DeActive</span></a>";
                }
                return act_html;
            }
        },
        {
            mData: null,
            bSortable: false,
            sWidth: "5%",
            sClass: "text-center",
            mRender: function(v, t, o) {
                var editurl = '{{ route("task.edit", ":id") }}';
                editurl = editurl.replace(':id',o['id']);
                var act_html = "<a href='"+editurl+"' data-toggle='tooltip' title='Edit Task' data-placement='top' class='btn btn-primary btn-sm'><i class='fa fa-fw fa-edit fa-lg'></i></a>"
                                +"&nbsp"
                                +"<a href='javascript:void(0)' data-name='"+o['name']+"' data-id='"+o['id']+"'  data-type='task' data-toggle='tooltip' title='Delete Task' data-placement='top' class='btn btn-sm btn-danger btn-delete'><i class='fa fa-fw fa-trash-o fa-lg'></i></a>"
                return act_html;
            }
        }, ],
        fnPreDrawCallback: function() {
            myShow();
        },
        fnDrawCallback: function(oSettings) {
            myHide();
        },
        fnRowCallback : function(nRow, aData, iDisplayIndex){
           $("td:first", nRow).html(iDisplayIndex +1);
           return nRow;
        },
    });

    task.fnSetFilteringDelay(1000);

    $("#task thead#filters input:text").donetyping(function() {
        task.fnFilter(this.value, $("#task thead#filters input:text").index(this));
    });
});
</script>
@stop