routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return redirect()->route('login');
});

Route::group(['prefix' => 'api'], function () {
    Route::get('group', [
        'as'   => 'group',
        'uses' => 'APIController@getGroup',
    ]);
    Route::get('task/{group}', [
        'as'   => 'task',
        'uses' => 'APIController@getTaskByGroupName',
    ]);
    Route::get('task/{taskId}/{status}', [
        'as'   => 'task',
        'uses' => 'APIController@updateStatus',
    ]);
});
Route::group(['middleware' => ['adminauth']], function () {
	Route::get('dashboard', [
        'as'   => 'dashboard',
        'uses' => 'DashboardController@index',
    ]);

    Route::group(['prefix' => 'change'], function () {
        Route::get('password', array(
            'as'   => 'changepassword.get',
            'uses' => 'UserController@getChangePassword',
        ));

        Route::post('password', array(
            'as'   => 'changepassword.post',
            'uses' => 'UserController@postChangePassword',
        ));
    });

    //Group routes start
    Route::group(['prefix' => 'group'], function () {
        Route::delete('delete', [
            'as'   => 'group.delete',
            'uses' => 'GroupController@delete',
        ]);

        Route::get('taskAssign', [
            'as'   => 'taskAssign',
            'uses' => 'GroupController@taskAssign',
        ]);
    });
    Route::resource('group', 'GroupController', ['except' => 'destroy', 'show']);
    //Group routes end
    
    //Task routes start
    Route::group(['prefix' => 'task'], function () {
        Route::delete('delete', [
            'as'   => 'task.delete',
            'uses' => 'TaskController@delete',
        ]);
    });
    Route::resource('task', 'TaskController', ['except' => 'destroy', 'show']);
    //Task routes end
    
    //Task User routes start
    Route::group(['prefix' => 'taskUser'], function () {
        Route::delete('delete', [
            'as'   => 'taskUser.delete',
            'uses' => 'TaskUserController@delete',
        ]);
    });
    Route::resource('taskUser', 'TaskUserController', ['except' => 'destroy', 'show']);
    //Task User routes end
    
    Route::get('taskAssign', [
        'as'   => 'taskAssign',
        'uses' => 'GroupController@taskAssign',
    ]);

    Route::post('taskAssign', [
        'as'   => 'taskAssign',
        'uses' => 'GroupController@taskAssignStore',
    ]);

    Route::get('groupAssign', [
        'as'   => 'groupAssign',
        'uses' => 'GroupController@groupAssign',
    ]);

    Route::post('groupAssign', [
        'as'   => 'groupAssign',
        'uses' => 'GroupController@groupAssignStore',
    ]);

    Route::get('logout', [
        'as'   => 'logout',
        'uses' => 'Auth\LoginController@logout',
    ]);
});

app/Http/Controllers/TaskUserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Model\TaskUser;
use Illuminate\Http\Request;
use Validator;
use View;

class TaskUserController extends Controller
{
    /**
     * [__construct description]
     */
    public function __construct()
    {
        parent::__construct();
        $this->viewPath = "taskUser";
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        View::share("title", "User");

        if ($request->ajax()) {
            $whereStr    = '1 = ?';
            $whereParams = [1];

            if ($request->has('sSearch')) {
                $search = trim(trim($request->get('sSearch')));
                $whereStr .= " and ( first_name like '%{$search}%'"
                    . ")";
            }

            $columns = ['id', 'first_name', 'last_name', 'email', 'mobile_no'];

            $taskUser = TaskUser::select($columns)
                ->whereRaw($whereStr, $whereParams)
                ->groupBy("task_user.id");

            $taskUserCount = TaskUser::select('id')
                ->whereRaw($whereStr, $whereParams)
                ->count();

            if ($request->has('iDisplayStart') && $request->get('iDisplayLength') != '-1') {
                $taskUser = $taskUser->take($request->get('iDisplayLength'))->skip($request->get('iDisplayStart'));
            }

            if ($request->has('iSortCol_0')) {
                $sql_order = '';
                for ($i = 0; $i < $request->get('iSortingCols'); $i++) {
                    $column = $columns[$request->get('iSortCol_' . $i)];
                    if (false !== ($index = strpos($column, ' as '))) {
                        $column = substr($column, 0, $index);
                    }
                    $taskUser = $taskUser->orderBy($column, $request->get('sSortDir_' . $i));
                }
            }

            $taskUser = $taskUser->get();

            $response['iTotalDisplayRecords'] = $taskUserCount;
            $response['iTotalRecords']        = $taskUserCount;
            $response['sEcho']                = intval($request->get('sEcho'));
            $response['aaData']               = $taskUser;
            return $response;
        }

        return view($this->viewPath . '.index');
    }

    /**
     * [create description]
     * @return [type] [description]
     */
    public function create()
    {
        View::share("title", "User");
        return view($this->viewPath . '.create');
    }

    /**
     * [store description]
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function store(Request $request)
    {
        $data  = $request->all();
        $rules = [
            'first_name' => "required|unique:task_user,first_name",
            'last_name'  => "required",
            'email'      => "required|email|unique:task_user,email",
            'mobile_no'  => "required|digits:10",
        ];
        $message = [
            'email.unique'      => 'The task user email must be unique',
            'first_name.unique' => 'The task user first name must be unique',
        ];
        $validator = Validator::make($data, $rules, $message);
        if ($validator->fails()) {
            return back()->withInput()
                ->withErrors($validator)
                ->with('message_type', 'danger')
                ->with('message', 'There were some error try again');
        }
        
        TaskUser::insert([
            'first_name' => $request->first_name,
            'last_name'  => $request->last_name,
            'email'      => $request->email,
            'mobile_no'  => $request->mobile_no,
            "created_at" => date("Y-m-d H:i:s"),
            "updated_at" => date("Y-m-d H:i:s"),
        ]);

        return back()->with('message_type', 'success')
            ->with('message', 'TaskUser Store Successfully');
    }

    /**
     * [edit description]
     * @param  [type] $id [description]
     * @return [type]     [description]
     */
    public function edit($id)
    {
        View::share("title", "User");
        $taskUser = TaskUser::where('id', $id)->first();
        return view($this->viewPath . '.edit', compact('taskUser'));
    }

    /**
     * [update description]
     * @param  Request $request [description]
     * @param  [type]  $id      [description]
     * @return [type]           [description]
     */
    public function update(Request $request, $id)
    {
        $data  = $request->all();

        $rules = [
            'first_name' => "required|unique:task_user,first_name,id,$id",
            'last_name'  => "required",
            'email'      => "required|email|unique:task_user,email,id,$id",
            'mobile_no'  => "required|digits:10",
        ];
        $message = [
            'email.unique'      => 'The task user email must be unique',
            'first_name.unique' => 'The task user first name must be unique',
        ];
        $validator = Validator::make($data, $rules, $message);
        if ($validator->fails()) {
            return back()->withInput()
                ->withErrors($validator)
                ->with('message_type', 'danger')
                ->with('message', 'There were some error try again');
        }

        $rules = [
            'name' => "required",
        ];
        $validator = Validator::make($data, $rules);
        if ($validator->fails()) {
            return back()->withInput()
                ->withErrors($validator)
                ->with('message_type', 'danger')
                ->with('message', 'There were some error try again');
        }
        TaskUser::where('id', $id)->update([
             'first_name' => $request->first_name,
            'last_name'  => $request->last_name,
            'email'      => $request->email,
            'mobile_no'  => $request->mobile_no,
            "updated_at" => date("Y-m-d H:i:s"),
        ]);
        return back()->with('message_type', 'success')
            ->with('message', 'TaskUser Updated Successfully');
    }

    /**
     * [delete description]
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function delete(Request $request)
    {
        View::share("title", "User");
        $ids = $request->id;
        if (!is_array($ids)) {
            $ids = explode(",", $ids);
        }
        TaskUser::whereIn('id', $ids)->delete();
        return response()->json(['success' => true], 200);
    }
}

resources/views/taskUser/create.blade.php
@extends($layoutTheme)
@section('content')
<div class="box box-warning">
	<div class="box-header with-border">
		<i class="fa fa-compass"></i>
		<h3 class="box-title">Create User</h3>
		<div class="pull-right box-tools">
			<a class="btn btn-success btn-sm" data-toggle="tooltip" title="Back" href="{!!route('taskUser.index')!!}"><i class="fa fa-lg fa fa-arrow-left"></i></a>
		</div>
		<!-- /. tools -->
	</div>
	<div class="box-body">
		<div class="row">
			{!! Form::open(array('url'=>route('taskUser.store'),'class' => 'form-horizontal')) !!}
			@include("taskUser.form")
		</div>
	</div>
	<div class="box-footer">
		<div class="form-group">
			<div class="col-sm-offset-2">
				<button type="submit" class="btn btn-success">
					<i class="fa fa-sliders" aria-hidden="true"></i> Save
				</button>
				<button type="reset" class="btn btn-default">
					<i class="fa fa-trash" aria-hidden="true"></i> Reset
				</button>
			</div>
		</div>
	</div>
	{!! Form::close() !!}
	<div id="spin" class="overlay" style="display:none;">
		<i class="fa fa-spin fa-spinner"></i>
	</div>
	<!-- /.box-body -->
</div>
@stop
@section('script')
<script type="text/javascript">
	$('form').submit(function(){
		myShow();
	});
</script>
@stop

resources/views/taskUser/edit.blade.php
@extends($layoutTheme)
@section('content')

<div class="box box-warning">
	<div class="box-header with-border">
		<h3 class="box-title">Edit Distributor</h3>
		<div class="pull-right box-tools">
			<a class="btn btn-success btn-sm" data-toggle="tooltip" title="Back" href="{{route('taskUser.index')}}"><i class="fa fa-lg fa fa-arrow-left"></i></a>
		</div>
		<!-- /. tools -->
	</div>
	<div class="box-body">
		<div class="row">
			{{ Form::model($taskUser,array('url'=>route('taskUser.update',$taskUser->id),'class' => 'form-horizontal','method' => 'PATCH' )) }}
			@include("taskUser.form")
		</div>
	</div>
	<div class="box-footer">
		<div class="form-group">
			<div class="col-sm-offset-2">
				<button type="submit" class="btn btn-success">
					<i class="fa fa-sliders" aria-hidden="true"></i> Save
				</button>
				<button type="reset" class="btn btn-default">
					<i class="fa fa-trash" aria-hidden="true"></i> Reset
				</button>
			</div>
		</div>
	</div>
	{{ Form::close() }}
	<div id="spin" class="overlay" style="display:none;">
		<i class="fa fa-spin fa-spinner"></i>
	</div>
	<!-- /.box-body -->
</div>
			
@stop
@section('script')
<script type="text/javascript">
	$('form').submit(function(){
		myShow();
	});
</script>
@stop

resources/views/taskUser/form.blade.php
<div class="form-group required">
	<label class="col-sm-2 control-label">First Name :-</label>
	<div class="col-sm-6">
		{!! Form::text('first_name',Input::old('first_name'),array('class'=>'form-control','placeholder'=>'First Name')) !!}
		{!! $errors->first('first_name','<span class="help-inline text-danger">:message</span>') !!}
	</div>
</div>

<div class="form-group required">
	<label class="col-sm-2 control-label">Last Name :-</label>
	<div class="col-sm-6">
		{!! Form::text('last_name',Input::old('last_name'),array('class'=>'form-control','placeholder'=>'Last Name')) !!}
		{!! $errors->first('last_name','<span class="help-inline text-danger">:message</span>') !!}
	</div>
</div>

<div class="form-group required">
	<label class="col-sm-2 control-label">Email :-</label>
	<div class="col-sm-6">
		{!! Form::text('email',Input::old('email'),array('class'=>'form-control','placeholder'=>'Email')) !!}
		{!! $errors->first('email','<span class="help-inline text-danger">:message</span>') !!}
	</div>
</div>

<div class="form-group required">
	<label class="col-sm-2 control-label">Mobile No :-</label>
	<div class="col-sm-6">
		{!! Form::text('mobile_no',Input::old('mobile_no'),array('class'=>'form-control numeric','placeholder'=>'Mobile No','maxlength' => '10')) !!}
		{!! $errors->first('mobile_no','<span class="help-inline text-danger">:message</span>') !!}
	</div>
</div>

resources/views/taskUser/index.blade.php
@extends($layoutTheme)
@section('content')

<div class="box box-info">
    <div class="box-header with-border">
        <i class="fa fa-compass"></i>
        <h3 class="box-title">All User </h3>
        <div class="pull-right box-tools">
            <a class="btn btn-success btn-sm" id='add_product' data-toggle="tooltip" title="Add User" href="{{ route('taskUser.create') }}"><i class="fa fa-fw fa-plus fa-lg"></i> </a>
        </div>
    </div>
    <div class="box-body">
        <table id='taskUser' class="table table-condensed table-bordered table-hover" style="width:100%">
            <thead>
                <tr>
                    <th style="padding-left:20px;">No</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Mobile No</th>
                    <th>Action</th>
                </tr>
            </thead>
            <thead id="filters">
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <div id="spin" class="overlay" style="display:none;">
        <i class="fa fa-spin fa-spinner"></i>
    </div>
    <!-- /.box-body -->
</div>
@stop

@section('script')

<script type="text/javascript">

$(function() {

    taskUser = $('#taskUser').dataTable({
        "bProcessing": false,
        "bServerSide": true,
        "bStateSave": true,
        "autoWidth": true,
        "sAjaxSource": "{{URL::route('taskUser.index')}}",
        "sPaginationType": "listbox",
        "aaSorting": [
            [1, "asc"]
        ],
        "oLanguage": {
          "sLengthMenu": "Display _MENU_ records"
        },
        "aoColumns": [
        { "mData": "id",sWidth: "05%",},
        { "mData": "first_name",sWidth: "15%",},
        { "mData": "last_name",sWidth: "15%",},
        { "mData": "email",sWidth: "10%",},
        { "mData": "mobile_no",sWidth: "10%",},
        {
            mData: null,
            bSortable: false,
            sWidth: "5%",
            sClass: "text-center",
            mRender: function(v, t, o) {
                var editurl = '{{ route("taskUser.edit", ":id") }}';
                editurl = editurl.replace(':id',o['id']);
                var act_html = "<a href='"+editurl+"' data-toggle='tooltip' title='Edit User' data-placement='top' class='btn btn-primary btn-sm'><i class='fa fa-fw fa-edit fa-lg'></i></a>"
                                +"&nbsp"
                                +"<a href='javascript:void(0)' data-name='"+o['first_name']+"' data-id='"+o['id']+"' data-type='taskUser' data-toggle='tooltip' title='Delete User' data-placement='top' class='btn btn-sm btn-danger btn-delete'><i class='fa fa-fw fa-trash-o fa-lg'></i></a>"
                return act_html;
            }
        }, ],
        fnPreDrawCallback: function() {
            myShow();
        },
        fnDrawCallback: function(oSettings) {
            myHide();
        },
        fnRowCallback : function(nRow, aData, iDisplayIndex){
           $("td:first", nRow).html(iDisplayIndex +1);
           return nRow;
        },
    });

    taskUser.fnSetFilteringDelay(1000);

    $("#taskUser thead#filters input:text").donetyping(function() {
        taskUser.fnFilter(this.value, $("#taskUser thead#filters input:text").index(this));
    });
});
</script>
@stop